FROM bitnami/minideb-runtimes:jessie

LABEL maintainer "mvranic@yahoo.com>"

ENV DEBIAN_FRONTEND noninteractive
ENV MAXWS 256M
#ENV ERRORONEXTERNALEXCEPTION 1

RUN install_packages build-essential ca-certificates curl git libbz2-1.0 libc6 libncurses5 libreadline6 libsqlite3-0 libssl1.0.0 libtinfo5 pkg-config unzip wget zlib1g

RUN apt-get update && \
	apt-get install -y apt-utils

RUN apt-get install -y unzip 

# Install Dyalog APL:
ADD dyalog-installation /dyalog
RUN cd /dyalog && \
	unzip *.zip && \
	dpkg -i *.deb && \
	find /opt/mdyalog -name make_scripts -exec {} \; && \
	rm -rf /dyalog

# prometheus support
# This look likes only for phyton:
# RUN pip install bottle==0.12.13 cherrypy==8.9.1 wsgi-request-logger prometheus_client

RUN mkdir /.dyalog
RUN chmod -R 777 /.dyalog
WORKDIR /

ADD Distribution/kubelessapl.dws /kubelessapl/

RUN git clone https://github.com/mvranic/JSONServer.git /JSONServer # Markos JSON Server with thread control.
#ADD JSONServer.dws /JSONServer/Distribution/

ADD aplcode /aplcode
RUN chmod -R 777 /aplcode

ADD entry.sh /scripts/
RUN sed -i -e 's/\r$//' /scripts/entry.sh

USER 1000

CMD ["/scripts/entry.sh"]